version: '3'

services:
  airmonitor:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: duchung0312/airmonitor:v0.0.1
    container_name: airmonitor
    restart: always
    privileged: true
    network_mode: host
    cgroup: host
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      NODE_ENV: production
      SQLITE_FILE_PATH: /var/lib/airmonitor/airmonitor-production.db
      SERVER_PORT: 1080
      TZ: Asia/Bangkok
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/airmonitor:/var/lib/airmonitor
      - /dev:/dev
      - /run/udev:/run/udev:ro
  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
